// <auto-generated />
using ASP_MVC_NoAuthentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP_MVC_NoAuthentication.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211205181113_FixedPaymentAndConnectors")]
    partial class FixedPaymentAndConnectors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaximumDistance")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.ChargingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfConnector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeOfCurrent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("ChargingPoints");
                });

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpenHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StationState")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChargingStations");
                });

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DrivingStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HighwaySpeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SummerFactor")
                        .HasColumnType("double");

                    b.Property<double>("WinterFactor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarConnector", b =>
                {
                    b.Property<int>("CarsId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorsId")
                        .HasColumnType("int");

                    b.HasKey("CarsId", "ConnectorsId");

                    b.HasIndex("ConnectorsId");

                    b.ToTable("CarConnector");
                });

            modelBuilder.Entity("ChargingStationPaymentMethod", b =>
                {
                    b.Property<int>("ChargingStationsId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodsId")
                        .HasColumnType("int");

                    b.HasKey("ChargingStationsId", "PaymentMethodsId");

                    b.HasIndex("PaymentMethodsId");

                    b.ToTable("ChargingStationPaymentMethod");
                });

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.ChargingPoint", b =>
                {
                    b.HasOne("ASP_MVC_NoAuthentication.Data.ChargingStation", "Station")
                        .WithMany("ChargingPoints")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("CarConnector", b =>
                {
                    b.HasOne("ASP_MVC_NoAuthentication.Data.Car", null)
                        .WithMany()
                        .HasForeignKey("CarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_MVC_NoAuthentication.Data.Connector", null)
                        .WithMany()
                        .HasForeignKey("ConnectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChargingStationPaymentMethod", b =>
                {
                    b.HasOne("ASP_MVC_NoAuthentication.Data.ChargingStation", null)
                        .WithMany()
                        .HasForeignKey("ChargingStationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_MVC_NoAuthentication.Data.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP_MVC_NoAuthentication.Data.ChargingStation", b =>
                {
                    b.Navigation("ChargingPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
